/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : Cpu.c
**     Project   : mcal
**     Processor : MC9S12XEP100MAG
**     Component : MC9S12XEP100_144
**     Version   : Component 01.003, Driver 02.06, CPU db: 3.00.036
**     Datasheet : MC9S12XEP100 Rev. 1.19 12/2008
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2016/6/12, 10:05
**     Abstract  :
**         This component "MC9S12XEP100_144" implements properties, methods,
**         and events of the CPU.
**     Settings  :
**
**     Contents  :
**         EnableInt   - void Cpu_EnableInt(void);
**         DisableInt  - void Cpu_DisableInt(void);
**         SetWaitMode - void Cpu_SetWaitMode(void);
**         SetStopMode - void Cpu_SetStopMode(void);
**         Delay100US  - void Cpu_Delay100US(word us100);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE Cpu. */

#include "wdi.h"
#include "Timer.h"
#include "CAN0.h"
#include "CAN1.h"
#include "CAN4.h"
#include "RELAY_HEAT.h"
#include "ISO_CTRL_POS.h"
#include "ISO_CTRL_NEG.h"
#include "CPUDI1.h"
#include "CPU_CS1.h"
#include "CPU_SCK.h"
#include "CPU_MOSI.h"
#include "CPU_MISO1.h"
#include "CPU_CS2.h"
#include "CPU_MISO2.h"
#include "CPU_SUMV_SDA.h"
#include "CPU_SUMV_SCL.h"
#include "CPU_SUMV_RDY.h"
#include "SUMV_POW.h"
#include "EN_POW2.h"
#include "BAL_SDA2.h"
#include "EN_POW1.h"
#include "BAL_SDA1.h"
#include "ExternFlash_Rst.h"
#include "ExternFlash_Cs.h"
#include "ExternFlash_Sck.h"
#include "ExternFlash_Si.h"
#include "ExternFlash_So.h"
#include "ExternTimer_Int.h"
#include "ExternTimer_Scl.h"
#include "ExternTimer_Sda.h"
#include "PORTA0.h"
#include "PORTA1.h"
#include "PORTA2.h"
#include "RELAY_POS.h"
#include "RELAY_NEG.h"
#include "RELAY_PRE.h"
#include "RELAY_FAN.h"
#include "AI1.h"
#include "CHG_CAN_POW.h"
#include "CPUCAN_CAR_EN.h"
#include "CPUCAN_INT_EN.h"
#include "CURPOWER.h"
#include "CPUCINT.h"
#include "CPUCSO.h"
#include "CPUCSI.h"
#include "CPUCSCK.h"
#include "CPUCCS.h"
#include "ExtEE_Sck.h"
#include "ExtEE_Sda.h"
#include "ExtEE_Wp.h"
#include "CPUEE.h"
#include "EN_POW3.h"
#include "EN_POW4.h"
#include "EN_CELL.h"
#include "DRDY_CELL.h"
#include "SPI2IF.h"
#include "IntWatchDog.h"
#include "CPUDI2.h"
#include "AC_CP_IOC.h"
#include "CPU_CHG_S.h"
#include "DO_CON.h"
#include "Events.h"
#include "TimerEvents.h"
#include "CAN0Events.h"
#include "CAN1Events.h"
#include "CAN4Events.h"
#include "AC_CP_IOCEvents.h"
#include "Cpu.h"

#define CGM_DELAY  0x17FFU

#pragma DATA_SEG DEFAULT               /* Select data segment "DEFAULT" */
#pragma CODE_SEG DEFAULT


/* Global variables */
volatile byte CCR_reg;                 /* Current CCR reegister */

/*Definition of global shadow variables*/
byte Shadow_K;
byte Shadow_C;
byte Shadow_M;
byte Shadow_S;
byte Shadow_H;
byte Shadow_D;
byte Shadow_J;

#pragma CODE_SEG __NEAR_SEG NON_BANKED


/*
** ===================================================================
**     Method      :  Cpu_Cpu_Interrupt (component MC9S12XEP100_144)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(Cpu_Interrupt)
{
  /*lint -save -e950 Disable MISRA rule (1.1) checking. */
  asm(BGND);
  /*lint -restore Enable MISRA rule (1.1) checking. */
}


/*
** ===================================================================
**     Method      :  Cpu_Delay100US (component MC9S12XEP100_144)
**
**     Description :
**         This method realizes software delay. The length of delay
**         is at least 100 microsecond multiply input parameter
**         [us100]. As the delay implementation is not based on real
**         clock, the delay time may be increased by interrupt
**         service routines processed during the delay. The method
**         is independent on selected speed mode.
**     Parameters  :
**         NAME            - DESCRIPTION
**         us100           - Number of 100 us delay repetitions.
**                         - The value of zero results in maximal 
**                           delay of approx. 6.5 seconds.
**     Returns     : Nothing
** ===================================================================
*/
#pragma NO_ENTRY                       /* Suppress generation of entry code in a function */
#pragma NO_EXIT                        /* Suppress generation of exit from a function */
#pragma MESSAGE DISABLE C5703          /*Disable C5703: Parameter ‘<Parameter>’ declared in function ‘<Function>’ but not referenced */
void Cpu_Delay100US(word us100)
{
  /* irremovable overhead (ignored): 13 cycles */
  /* ldd:  2 cycles overhead (load parameter into register) */
  /* jsr:  4 cycles overhead (call this function) */
  /* rts:  7 cycles overhead (return from this function) */

  /* irremovable overhead for each 100us cycle (counted): 13 cycles */
  /* dbne:  3 cycles overhead (return from this function) */

  /*lint -save  -e950 -e522 Disable MISRA rule (1.1,14.2) checking. */
  asm {
    loop:
    /* 100 us delay block begin */
    /*
     * Delay
     *   - requested                  : 100 us @ 48MHz,
     *   - possible                   : 4800 c, 100000 ns
     *   - without removable overhead : 4797 c, 99937.5 ns
     */
    pshd                               /* (2 c: 41.67 ns) backup D */
    ldd #$01B3                         /* (2 c: 41.67 ns) number of iterations */
    label0:
    movb #85,ARMCOP                    /* Reset watchdog counter - 2x write*/
    movb #170,ARMCOP
    dbne d, label0                     /* (3 c: 62.5 ns) repeat 435x */
    puld                               /* (3 c: 62.5 ns) restore D */
    nop                                /* (1 c: 20.83 ns) wait for 1 c */
    nop                                /* (1 c: 20.83 ns) wait for 1 c */
    nop                                /* (1 c: 20.83 ns) wait for 1 c */
    nop                                /* (1 c: 20.83 ns) wait for 1 c */
    nop                                /* (1 c: 20.83 ns) wait for 1 c */
    /* 100 us delay block end */
    dbne d, loop                       /* us100 parameter is passed via D register */
    rts                                /* return from subroutine */
  };
  /*lint -restore Enable MISRA rule (1.1,14.2) checking. */
}

#pragma CODE_SEG DEFAULT

/*
** ===================================================================
**     Method      :  Cpu_DisableInt (component MC9S12XEP100_144)
**
**     Description :
**         Disable maskable interrupts
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_DisableInt(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_EnableInt (component MC9S12XEP100_144)
**
**     Description :
**         Enable maskable interrupts
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_EnableInt(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_SetStopMode (component MC9S12XEP100_144)
**
**     Description :
**         Set low power mode - Stop mode.
**         For more information about the stop mode see
**         documentation of this CPU.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_SetStopMode(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_SetWaitMode (component MC9S12XEP100_144)
**
**     Description :
**         Set low power mode - Wait mode.
**         For more information about the wait mode see
**         documentation of this CPU.
**         Release from Wait mode: Reset or interrupt
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_SetWaitMode(void)

**      This method is implemented as macro in the header module. **
*/

#pragma OPTION ADD "-Onf"              /* Disable 'Create Sub-Functions with Common Code optimalization' */
/*
** ===================================================================
**     Method      :  PE_low_level_init (component MC9S12XEP100_144)
**
**     Description :
**         Initializes components and provides common register 
**         initialization. The method is called automatically as a part 
**         of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void PE_low_level_init(void)
{
  /* Int. priority initialization */
  /*                                        No. Address Pri XGATE Name            Description */
  setReg8(INT_CFADDR, 0x90U);           
  setReg8(INT_CFDATA0, 0x04U);         /*  0x48  0xFF90   4   no   ivVcan4tx       used by PE */ 
  setReg8(INT_CFDATA1, 0x04U);         /*  0x49  0xFF92   4   no   ivVcan4rx       used by PE */ 
  setReg8(INT_CFDATA2, 0x04U);         /*  0x4A  0xFF94   4   no   ivVcan4err      used by PE */ 
  setReg8(INT_CFADDR, 0xA0U);           
  setReg8(INT_CFDATA4, 0x04U);         /*  0x54  0xFFA8   4   no   ivVcan1tx       used by PE */ 
  setReg8(INT_CFDATA5, 0x04U);         /*  0x55  0xFFAA   4   no   ivVcan1rx       used by PE */ 
  setReg8(INT_CFDATA6, 0x04U);         /*  0x56  0xFFAC   4   no   ivVcan1err      used by PE */ 
  setReg8(INT_CFADDR, 0xB0U);           
  setReg8(INT_CFDATA0, 0x04U);         /*  0x58  0xFFB0   4   no   ivVcan0tx       used by PE */ 
  setReg8(INT_CFDATA1, 0x04U);         /*  0x59  0xFFB2   4   no   ivVcan0rx       used by PE */ 
  setReg8(INT_CFDATA2, 0x04U);         /*  0x5A  0xFFB4   4   no   ivVcan0err      used by PE */ 
  setReg8(INT_CFADDR, 0xC0U);           
  setReg8(INT_CFDATA5, 0x04U);         /*  0x65  0xFFCA   4   no   ivVectmdcu      used by PE */ 
  setReg8(INT_CFADDR, 0xE0U);           
  setReg8(INT_CFDATA2, 0x04U);         /*  0x72  0xFFE4   4   no   ivVectch5       used by PE */ 
  /* Initialization of Memory Protection unit */
  /* MPUSEL: SVSEN=0,??=0,??=0,??=0,??=0,SEL=1 */
  setReg8(MPUSEL, 0x01U);              /* Select Descriptor num. 1 */ 
  /* MPUDESC2: LOW_ADDR10=0,LOW_ADDR9=0,LOW_ADDR8=0,LOW_ADDR7=0,LOW_ADDR6=0,LOW_ADDR5=0,LOW_ADDR4=0,LOW_ADDR3=0 */
  setReg8(MPUDESC2, 0x00U);             
  /* MPUDESC1: LOW_ADDR18=0,LOW_ADDR17=0,LOW_ADDR16=0,LOW_ADDR15=0,LOW_ADDR14=0,LOW_ADDR13=0,LOW_ADDR12=0,LOW_ADDR11=0 */
  setReg8(MPUDESC1, 0x00U);             
  /* MPUDESC0: MSTR0=0,MSTR1=0,MSTR2=0,MSTR3=0,LOW_ADDR22=0,LOW_ADDR21=0,LOW_ADDR20=0,LOW_ADDR19=0 */
  setReg8(MPUDESC0, 0x00U);             
  /* MPUDESC5: HIGH_ADDR10=1,HIGH_ADDR9=1,HIGH_ADDR8=1,HIGH_ADDR7=1,HIGH_ADDR6=1,HIGH_ADDR5=1,HIGH_ADDR4=1,HIGH_ADDR3=1 */
  setReg8(MPUDESC5, 0xFFU);             
  /* MPUDESC4: HIGH_ADDR18=1,HIGH_ADDR17=1,HIGH_ADDR16=1,HIGH_ADDR15=1,HIGH_ADDR14=1,HIGH_ADDR13=1,HIGH_ADDR12=1,HIGH_ADDR11=1 */
  setReg8(MPUDESC4, 0xFFU);             
  /* MPUDESC3: WP=0,NEX=0,??=0,??=0,HIGH_ADDR22=1,HIGH_ADDR21=1,HIGH_ADDR20=1,HIGH_ADDR19=1 */
  setReg8(MPUDESC3, 0x0FU);             
  /* MPUSEL: SVSEN=0,??=0,??=0,??=0,??=0,SEL=2 */
  setReg8(MPUSEL, 0x02U);              /* Select Descriptor num. 2 */ 
  /* MPUDESC2: LOW_ADDR10=0,LOW_ADDR9=0,LOW_ADDR8=0,LOW_ADDR7=0,LOW_ADDR6=0,LOW_ADDR5=0,LOW_ADDR4=0,LOW_ADDR3=0 */
  setReg8(MPUDESC2, 0x00U);             
  /* MPUDESC1: LOW_ADDR18=0,LOW_ADDR17=0,LOW_ADDR16=0,LOW_ADDR15=0,LOW_ADDR14=0,LOW_ADDR13=0,LOW_ADDR12=0,LOW_ADDR11=0 */
  setReg8(MPUDESC1, 0x00U);             
  /* MPUDESC0: MSTR0=0,MSTR1=0,MSTR2=0,MSTR3=0,LOW_ADDR22=0,LOW_ADDR21=0,LOW_ADDR20=0,LOW_ADDR19=0 */
  setReg8(MPUDESC0, 0x00U);             
  /* MPUDESC5: HIGH_ADDR10=1,HIGH_ADDR9=1,HIGH_ADDR8=1,HIGH_ADDR7=1,HIGH_ADDR6=1,HIGH_ADDR5=1,HIGH_ADDR4=1,HIGH_ADDR3=1 */
  setReg8(MPUDESC5, 0xFFU);             
  /* MPUDESC4: HIGH_ADDR18=1,HIGH_ADDR17=1,HIGH_ADDR16=1,HIGH_ADDR15=1,HIGH_ADDR14=1,HIGH_ADDR13=1,HIGH_ADDR12=1,HIGH_ADDR11=1 */
  setReg8(MPUDESC4, 0xFFU);             
  /* MPUDESC3: WP=0,NEX=0,??=0,??=0,HIGH_ADDR22=1,HIGH_ADDR21=1,HIGH_ADDR20=1,HIGH_ADDR19=1 */
  setReg8(MPUDESC3, 0x0FU);             
  /* MPUSEL: SVSEN=0,??=0,??=0,??=0,??=0,SEL=3 */
  setReg8(MPUSEL, 0x03U);              /* Select Descriptor num. 3 */ 
  /* MPUDESC2: LOW_ADDR10=0,LOW_ADDR9=0,LOW_ADDR8=0,LOW_ADDR7=0,LOW_ADDR6=0,LOW_ADDR5=0,LOW_ADDR4=0,LOW_ADDR3=0 */
  setReg8(MPUDESC2, 0x00U);             
  /* MPUDESC1: LOW_ADDR18=0,LOW_ADDR17=0,LOW_ADDR16=0,LOW_ADDR15=0,LOW_ADDR14=0,LOW_ADDR13=0,LOW_ADDR12=0,LOW_ADDR11=0 */
  setReg8(MPUDESC1, 0x00U);             
  /* MPUDESC0: MSTR0=0,MSTR1=0,MSTR2=0,MSTR3=0,LOW_ADDR22=0,LOW_ADDR21=0,LOW_ADDR20=0,LOW_ADDR19=0 */
  setReg8(MPUDESC0, 0x00U);             
  /* MPUDESC5: HIGH_ADDR10=1,HIGH_ADDR9=1,HIGH_ADDR8=1,HIGH_ADDR7=1,HIGH_ADDR6=1,HIGH_ADDR5=1,HIGH_ADDR4=1,HIGH_ADDR3=1 */
  setReg8(MPUDESC5, 0xFFU);             
  /* MPUDESC4: HIGH_ADDR18=1,HIGH_ADDR17=1,HIGH_ADDR16=1,HIGH_ADDR15=1,HIGH_ADDR14=1,HIGH_ADDR13=1,HIGH_ADDR12=1,HIGH_ADDR11=1 */
  setReg8(MPUDESC4, 0xFFU);             
  /* MPUDESC3: WP=0,NEX=0,??=0,??=0,HIGH_ADDR22=1,HIGH_ADDR21=1,HIGH_ADDR20=1,HIGH_ADDR19=1 */
  setReg8(MPUDESC3, 0x0FU);             
  /* MPUSEL: SVSEN=0,??=0,??=0,??=0,??=0,SEL=4 */
  setReg8(MPUSEL, 0x04U);              /* Select Descriptor num. 4 */ 
  /* MPUDESC2: LOW_ADDR10=0,LOW_ADDR9=0,LOW_ADDR8=0,LOW_ADDR7=0,LOW_ADDR6=0,LOW_ADDR5=0,LOW_ADDR4=0,LOW_ADDR3=0 */
  setReg8(MPUDESC2, 0x00U);             
  /* MPUDESC1: LOW_ADDR18=0,LOW_ADDR17=0,LOW_ADDR16=0,LOW_ADDR15=0,LOW_ADDR14=0,LOW_ADDR13=0,LOW_ADDR12=0,LOW_ADDR11=0 */
  setReg8(MPUDESC1, 0x00U);             
  /* MPUDESC0: MSTR0=0,MSTR1=0,MSTR2=0,MSTR3=0,LOW_ADDR22=0,LOW_ADDR21=0,LOW_ADDR20=0,LOW_ADDR19=0 */
  setReg8(MPUDESC0, 0x00U);             
  /* MPUDESC5: HIGH_ADDR10=1,HIGH_ADDR9=1,HIGH_ADDR8=1,HIGH_ADDR7=1,HIGH_ADDR6=1,HIGH_ADDR5=1,HIGH_ADDR4=1,HIGH_ADDR3=1 */
  setReg8(MPUDESC5, 0xFFU);             
  /* MPUDESC4: HIGH_ADDR18=1,HIGH_ADDR17=1,HIGH_ADDR16=1,HIGH_ADDR15=1,HIGH_ADDR14=1,HIGH_ADDR13=1,HIGH_ADDR12=1,HIGH_ADDR11=1 */
  setReg8(MPUDESC4, 0xFFU);             
  /* MPUDESC3: WP=0,NEX=0,??=0,??=0,HIGH_ADDR22=1,HIGH_ADDR21=1,HIGH_ADDR20=1,HIGH_ADDR19=1 */
  setReg8(MPUDESC3, 0x0FU);             
  /* MPUSEL: SVSEN=0,??=0,??=0,??=0,??=0,SEL=5 */
  setReg8(MPUSEL, 0x05U);              /* Select Descriptor num. 5 */ 
  /* MPUDESC2: LOW_ADDR10=0,LOW_ADDR9=0,LOW_ADDR8=0,LOW_ADDR7=0,LOW_ADDR6=0,LOW_ADDR5=0,LOW_ADDR4=0,LOW_ADDR3=0 */
  setReg8(MPUDESC2, 0x00U);             
  /* MPUDESC1: LOW_ADDR18=0,LOW_ADDR17=0,LOW_ADDR16=0,LOW_ADDR15=0,LOW_ADDR14=0,LOW_ADDR13=0,LOW_ADDR12=0,LOW_ADDR11=0 */
  setReg8(MPUDESC1, 0x00U);             
  /* MPUDESC0: MSTR0=0,MSTR1=0,MSTR2=0,MSTR3=0,LOW_ADDR22=0,LOW_ADDR21=0,LOW_ADDR20=0,LOW_ADDR19=0 */
  setReg8(MPUDESC0, 0x00U);             
  /* MPUDESC5: HIGH_ADDR10=1,HIGH_ADDR9=1,HIGH_ADDR8=1,HIGH_ADDR7=1,HIGH_ADDR6=1,HIGH_ADDR5=1,HIGH_ADDR4=1,HIGH_ADDR3=1 */
  setReg8(MPUDESC5, 0xFFU);             
  /* MPUDESC4: HIGH_ADDR18=1,HIGH_ADDR17=1,HIGH_ADDR16=1,HIGH_ADDR15=1,HIGH_ADDR14=1,HIGH_ADDR13=1,HIGH_ADDR12=1,HIGH_ADDR11=1 */
  setReg8(MPUDESC4, 0xFFU);             
  /* MPUDESC3: WP=0,NEX=0,??=0,??=0,HIGH_ADDR22=1,HIGH_ADDR21=1,HIGH_ADDR20=1,HIGH_ADDR19=1 */
  setReg8(MPUDESC3, 0x0FU);             
  /* MPUSEL: SVSEN=0,??=0,??=0,??=0,??=0,SEL=6 */
  setReg8(MPUSEL, 0x06U);              /* Select Descriptor num. 6 */ 
  /* MPUDESC2: LOW_ADDR10=0,LOW_ADDR9=0,LOW_ADDR8=0,LOW_ADDR7=0,LOW_ADDR6=0,LOW_ADDR5=0,LOW_ADDR4=0,LOW_ADDR3=0 */
  setReg8(MPUDESC2, 0x00U);             
  /* MPUDESC1: LOW_ADDR18=0,LOW_ADDR17=0,LOW_ADDR16=0,LOW_ADDR15=0,LOW_ADDR14=0,LOW_ADDR13=0,LOW_ADDR12=0,LOW_ADDR11=0 */
  setReg8(MPUDESC1, 0x00U);             
  /* MPUDESC0: MSTR0=0,MSTR1=0,MSTR2=0,MSTR3=0,LOW_ADDR22=0,LOW_ADDR21=0,LOW_ADDR20=0,LOW_ADDR19=0 */
  setReg8(MPUDESC0, 0x00U);             
  /* MPUDESC5: HIGH_ADDR10=1,HIGH_ADDR9=1,HIGH_ADDR8=1,HIGH_ADDR7=1,HIGH_ADDR6=1,HIGH_ADDR5=1,HIGH_ADDR4=1,HIGH_ADDR3=1 */
  setReg8(MPUDESC5, 0xFFU);             
  /* MPUDESC4: HIGH_ADDR18=1,HIGH_ADDR17=1,HIGH_ADDR16=1,HIGH_ADDR15=1,HIGH_ADDR14=1,HIGH_ADDR13=1,HIGH_ADDR12=1,HIGH_ADDR11=1 */
  setReg8(MPUDESC4, 0xFFU);             
  /* MPUDESC3: WP=0,NEX=0,??=0,??=0,HIGH_ADDR22=1,HIGH_ADDR21=1,HIGH_ADDR20=1,HIGH_ADDR19=1 */
  setReg8(MPUDESC3, 0x0FU);             
  /* MPUSEL: SVSEN=0,??=0,??=0,??=0,??=0,SEL=7 */
  setReg8(MPUSEL, 0x07U);              /* Select Descriptor num. 7 */ 
  /* MPUDESC2: LOW_ADDR10=0,LOW_ADDR9=0,LOW_ADDR8=0,LOW_ADDR7=0,LOW_ADDR6=0,LOW_ADDR5=0,LOW_ADDR4=0,LOW_ADDR3=0 */
  setReg8(MPUDESC2, 0x00U);             
  /* MPUDESC1: LOW_ADDR18=0,LOW_ADDR17=0,LOW_ADDR16=0,LOW_ADDR15=0,LOW_ADDR14=0,LOW_ADDR13=0,LOW_ADDR12=0,LOW_ADDR11=0 */
  setReg8(MPUDESC1, 0x00U);             
  /* MPUDESC0: MSTR0=0,MSTR1=0,MSTR2=0,MSTR3=0,LOW_ADDR22=0,LOW_ADDR21=0,LOW_ADDR20=0,LOW_ADDR19=0 */
  setReg8(MPUDESC0, 0x00U);             
  /* MPUDESC5: HIGH_ADDR10=1,HIGH_ADDR9=1,HIGH_ADDR8=1,HIGH_ADDR7=1,HIGH_ADDR6=1,HIGH_ADDR5=1,HIGH_ADDR4=1,HIGH_ADDR3=1 */
  setReg8(MPUDESC5, 0xFFU);             
  /* MPUDESC4: HIGH_ADDR18=1,HIGH_ADDR17=1,HIGH_ADDR16=1,HIGH_ADDR15=1,HIGH_ADDR14=1,HIGH_ADDR13=1,HIGH_ADDR12=1,HIGH_ADDR11=1 */
  setReg8(MPUDESC4, 0xFFU);             
  /* MPUDESC3: WP=0,NEX=0,??=0,??=0,HIGH_ADDR22=1,HIGH_ADDR21=1,HIGH_ADDR20=1,HIGH_ADDR19=1 */
  setReg8(MPUDESC3, 0x0FU);             
  /* MPUSEL: SVSEN=0,??=0,??=0,??=0,??=0,SEL=0 */
  setReg8(MPUSEL, 0x00U);              /* Select Descriptor num. 0 */ 
  /* MPUDESC2: LOW_ADDR10=0,LOW_ADDR9=0,LOW_ADDR8=0,LOW_ADDR7=0,LOW_ADDR6=0,LOW_ADDR5=0,LOW_ADDR4=0,LOW_ADDR3=0 */
  setReg8(MPUDESC2, 0x00U);             
  /* MPUDESC1: LOW_ADDR18=0,LOW_ADDR17=0,LOW_ADDR16=0,LOW_ADDR15=0,LOW_ADDR14=0,LOW_ADDR13=0,LOW_ADDR12=0,LOW_ADDR11=0 */
  setReg8(MPUDESC1, 0x00U);             
  /* MPUDESC0: MSTR0=1,MSTR1=1,MSTR2=1,MSTR3=0,LOW_ADDR22=0,LOW_ADDR21=0,LOW_ADDR20=0,LOW_ADDR19=0 */
  setReg8(MPUDESC0, 0xE0U);             
  /* MPUDESC5: HIGH_ADDR10=1,HIGH_ADDR9=1,HIGH_ADDR8=1,HIGH_ADDR7=1,HIGH_ADDR6=1,HIGH_ADDR5=1,HIGH_ADDR4=1,HIGH_ADDR3=1 */
  setReg8(MPUDESC5, 0xFFU);             
  /* MPUDESC4: HIGH_ADDR18=1,HIGH_ADDR17=1,HIGH_ADDR16=1,HIGH_ADDR15=1,HIGH_ADDR14=1,HIGH_ADDR13=1,HIGH_ADDR12=1,HIGH_ADDR11=1 */
  setReg8(MPUDESC4, 0xFFU);             
  /* MPUDESC3: WP=0,NEX=0,??=0,??=0,HIGH_ADDR22=1,HIGH_ADDR21=1,HIGH_ADDR20=1,HIGH_ADDR19=1 */
  setReg8(MPUDESC3, 0x0FU);             
  /* Common initialization of the CPU registers */
  /* PORTB: PB6=0,PB5=0,PB3=0,PB2=0,PB1=0 */
  clrReg8Bits(PORTB, 0x6EU);            
  /* PUCR: PUPKE=0,PUPDE=0,PUPCE=0,PUPBE=0,PUPAE=0 */
  clrReg8Bits(PUCR, 0x8FU);             
  /* DDRB: DDRB7=0,DDRB6=1,DDRB5=1,DDRB4=0,DDRB3=1,DDRB2=1,DDRB1=1 */
  clrSetReg8Bits(DDRB, 0x90U, 0x6EU);   
  /* ECT_TSCR1: TEN=0,TSWAI=0,TSFRZ=0,TFFCA=0,PRNT=0,??=0,??=0,??=0 */
  setReg8(ECT_TSCR1, 0x00U);            
  /* ECT_MCCTL: MODMC=1,RDMCL=0,MCEN=0,MCPR1=0,MCPR0=1 */
  clrSetReg8Bits(ECT_MCCTL, 0x26U, 0x41U); 
  /* MODRR: MODRR6=0,MODRR3=0,MODRR2=1,MODRR1=0,MODRR0=0 */
  clrSetReg8Bits(MODRR, 0x4BU, 0x04U);  
  /* PORTK: PK7=0,PK6=0,PK5=0,PK4=0,PK2=0,PK1=0 */
  clrReg8Bits(PORTK, 0xF6U);            
  /* DDRK: DDRK7=1,DDRK6=1,DDRK5=1,DDRK4=1,DDRK2=1,DDRK1=1 */
  setReg8Bits(DDRK, 0xF6U);             
  /* PERT: PERT6=0,PERT5=0,PERT4=0,PERT2=0,PERT1=0 */
  clrReg8Bits(PERT, 0x76U);             
  /* PTT: PTT6=1,PTT4=1 */
  setReg8Bits(PTT, 0x50U);              
  /* DDRT: DDRT6=1,DDRT4=1,DDRT2=0,DDRT1=0 */
  clrSetReg8Bits(DDRT, 0x06U, 0x50U);   
  /* PIEJ: PIEJ7=0,PIEJ6=0,PIEJ2=0,PIEJ1=0,PIEJ0=0 */
  clrReg8Bits(PIEJ, 0xC7U);             
  /* PERJ: PERJ7=0,PERJ6=0,PERJ2=0,PERJ1=0,PERJ0=0 */
  clrReg8Bits(PERJ, 0xC7U);             
  /* PTJ: PTJ7=0,PTJ6=0,PTJ2=0,PTJ0=1 */
  clrSetReg8Bits(PTJ, 0xC4U, 0x01U);    
  /* DDRJ: DDRJ7=1,DDRJ6=1,DDRJ3=1,DDRJ2=1,DDRJ1=0,DDRJ0=1 */
  clrSetReg8Bits(DDRJ, 0x02U, 0xCDU);   
  /* PORTC: PC3=1,PC2=1,PC1=1,PC0=1 */
  setReg8Bits(PORTC, 0x0FU);            
  /* DDRC: DDRC3=1,DDRC2=1,DDRC1=1,DDRC0=1 */
  setReg8Bits(DDRC, 0x0FU);             
  /* PTM: PTM7=0,PTM6=0 */
  clrReg8Bits(PTM, 0xC0U);              
  /* WOMM: WOMM7=1,WOMM6=1 */
  setReg8Bits(WOMM, 0xC0U);             
  /* PERM: PERM7=0,PERM6=0 */
  clrReg8Bits(PERM, 0xC0U);             
  /* DDRM: DDRM7=1,DDRM6=1 */
  setReg8Bits(DDRM, 0xC0U);             
  /* PTS: PTS7=0,PTS6=0,PTS5=0,PTS2=0,PTS1=0,PTS0=1 */
  clrSetReg8Bits(PTS, 0xE6U, 0x01U);    
  /* WOMS: WOMS7=0,WOMS6=0,WOMS5=0,WOMS2=1,WOMS1=1,WOMS0=0 */
  clrSetReg8Bits(WOMS, 0xE1U, 0x06U);   
  /* PERS: PERS4=0,PERS3=0,PERS2=0,PERS1=0 */
  clrReg8Bits(PERS, 0x1EU);             
  /* DDRS: DDRS7=1,DDRS6=1,DDRS5=1,DDRS4=0,DDRS3=0,DDRS2=1,DDRS1=1,DDRS0=1 */
  setReg8(DDRS, 0xE7U);                 
  /* PIEH: PIEH4=0 */
  clrReg8Bits(PIEH, 0x10U);             
  /* PTH: PTH4=0 */
  clrReg8Bits(PTH, 0x10U);              
  /* PERH: PERH4=0 */
  clrReg8Bits(PERH, 0x10U);             
  /* DDRH: DDRH4=0 */
  clrReg8Bits(DDRH, 0x10U);             
  /* PORTD: PD3=0,PD2=0 */
  clrReg8Bits(PORTD, 0x0CU);            
  /* DDRD: DDRD3=1,DDRD2=1,DDRD1=0 */
  clrSetReg8Bits(DDRD, 0x02U, 0x0CU);   
  /* PORTA: PA6=1,PA4=1,PA3=0 */
  clrSetReg8Bits(PORTA, 0x08U, 0x50U);  
  /* DDRA: DDRA6=1,DDRA4=1,DDRA3=1,DDRA2=0,DDRA1=0,DDRA0=0 */
  clrSetReg8Bits(DDRA, 0x07U, 0x58U);   
  /* PIEP: PIEP3=0,PIEP2=0,PIEP1=0,PIEP0=0 */
  clrReg8Bits(PIEP, 0x0FU);             
  /* PTP: PTP7=0,PTP6=1,PTP3=0,PTP2=0,PTP1=0,PTP0=0 */
  clrSetReg8Bits(PTP, 0x8FU, 0x40U);    
  /* PERP: PERP3=0,PERP2=0,PERP1=0,PERP0=0 */
  clrReg8Bits(PERP, 0x0FU);             
  /* DDRP: DDRP7=1,DDRP6=1,DDRP5=1,DDRP4=0,DDRP3=1,DDRP2=1,DDRP1=1,DDRP0=1 */
  setReg8(DDRP, 0xEFU);                 
  /* ATD1DIENL: IEN7=1,IEN1=1,IEN0=1 */
  setReg8Bits(ATD1DIENL, 0x83U);        
  /* PT1AD1: PT1AD17=1,PT1AD10=0 */
  clrSetReg8Bits(PT1AD1, 0x01U, 0x80U); 
  /* PER1AD1: PER1AD17=0,PER1AD11=0,PER1AD10=0 */
  clrReg8Bits(PER1AD1, 0x83U);          
  /* DDR1AD1: DDR1AD17=1,DDR1AD11=0,DDR1AD10=1 */
  clrSetReg8Bits(DDR1AD1, 0x02U, 0x81U); 
  /* PLLCTL: PCE=0 */
  clrReg8Bits(PLLCTL, 0x02U);           
  /* COPCTL: WCOP=0,RSBCK=1,CR2=1,CR1=0,CR0=1 */
  clrSetReg8Bits(COPCTL, 0x82U, 0x45U); 
  /* ECT_TCTL3: EDG5B=0,EDG5A=0 */
  clrReg8Bits(ECT_TCTL3, 0x0CU);        
  /* ECT_TIE: C5I=0 */
  clrReg8Bits(ECT_TIE, 0x20U);          
  /* ECT_TIOS: IOS5=0 */
  clrReg8Bits(ECT_TIOS, 0x20U);         
  /* ECT_ICOVW: NOVW5=0 */
  clrReg8Bits(ECT_ICOVW, 0x20U);        
  /* ECT_DLYCT: DLY7=0,DLY6=0,DLY5=0,DLY4=0,DLY3=0,DLY2=0,DLY1=0,DLY0=0 */
  setReg8(ECT_DLYCT, 0x00U);            
  /* ECT_ICSYS: SH37=0,SH26=0,SH15=0,SH04=0,TFMOD=0,BUFEN=0,LATQ=0 */
  clrReg8Bits(ECT_ICSYS, 0xFBU);        
  /* ECT_PACTL: CLK1=0,CLK0=0 */
  clrReg8Bits(ECT_PACTL, 0x0CU);        
  /* CRGINT: LOCKIE=0,SCMIE=0 */
  clrReg8Bits(CRGINT, 0x12U);           
  /* VREGCTRL: LVIE=0 */
  clrReg8Bits(VREGCTRL, 0x02U);         
  /* DDR0AD1: DDR0AD17=1,DDR0AD16=1,DDR0AD15=1,DDR0AD14=1,DDR0AD13=1,DDR0AD12=1,DDR0AD11=1,DDR0AD10=1 */
  setReg8(DDR0AD1, 0xFFU);              
  /* DDRF: DDRF7=1,DDRF6=1,DDRF5=1,DDRF4=1,DDRF3=1,DDRF2=1,DDRF1=1,DDRF0=1 */
  setReg8(DDRF, 0xFFU);                 
  /* DDRL: DDRL7=1,DDRL6=1,DDRL5=1,DDRL4=1,DDRL3=1,DDRL2=1,DDRL1=1,DDRL0=1 */
  setReg8(DDRL, 0xFFU);                 
  /* DDRR: DDRR7=1,DDRR6=1,DDRR5=1,DDRR4=1,DDRR3=1,DDRR2=1,DDRR1=1,DDRR0=1 */
  setReg8(DDRR, 0xFFU);                 
  /* RDRIV: RDPK=0,RDPE=0,RDPD=0,RDPC=0,RDPB=0,RDPA=0 */
  clrReg8Bits(RDRIV, 0x9FU);            
  /* RDR1AD1: RDR1AD17=0,RDR1AD16=0,RDR1AD15=0,RDR1AD14=0,RDR1AD13=0,RDR1AD12=0,RDR1AD11=0,RDR1AD10=0 */
  setReg8(RDR1AD1, 0x00U);              
  /* RDRH: RDRH7=0,RDRH6=0,RDRH5=0,RDRH4=0,RDRH3=0,RDRH2=0,RDRH1=0,RDRH0=0 */
  setReg8(RDRH, 0x00U);                 
  /* RDRJ: RDRJ7=0,RDRJ6=0,RDRJ5=0,RDRJ4=0,RDRJ2=0,RDRJ1=0,RDRJ0=0 */
  clrReg8Bits(RDRJ, 0xF7U);             
  /* RDRM: RDRM7=0,RDRM6=0,RDRM5=0,RDRM4=0,RDRM3=0,RDRM2=0,RDRM1=0,RDRM0=0 */
  setReg8(RDRM, 0x00U);                 
  /* RDRP: RDRP7=0,RDRP6=0,RDRP5=0,RDRP4=0,RDRP3=0,RDRP2=0,RDRP1=0,RDRP0=0 */
  setReg8(RDRP, 0x00U);                 
  /* RDRS: RDRS7=0,RDRS6=0,RDRS5=0,RDRS4=0,RDRS3=0,RDRS2=0,RDRS1=0,RDRS0=0 */
  setReg8(RDRS, 0x00U);                 
  /* RDRT: RDRT7=0,RDRT6=0,RDRT5=0,RDRT4=0,RDRT3=0,RDRT2=0,RDRT1=0,RDRT0=0 */
  setReg8(RDRT, 0x00U);                 
  /* RDR0AD0: RDR0AD07=0,RDR0AD06=0,RDR0AD05=0,RDR0AD04=0,RDR0AD03=0,RDR0AD02=0,RDR0AD01=0,RDR0AD00=0 */
  setReg8(RDR0AD0, 0x00U);              
  /* RDR1AD0: RDR1AD07=0,RDR1AD06=0,RDR1AD05=0,RDR1AD04=0,RDR1AD03=0,RDR1AD02=0,RDR1AD01=0,RDR1AD00=0 */
  setReg8(RDR1AD0, 0x00U);              
  /* IRQCR: IRQEN=0 */
  clrReg8Bits(IRQCR, 0x40U);            
  /* ATD0DIEN: IEN15=0,IEN14=0,IEN13=0,IEN12=0,IEN11=0,IEN10=0,IEN9=0,IEN8=0,IEN7=0,IEN6=0,IEN5=0,IEN3=0,IEN2=0,IEN1=0,IEN0=0 */
  clrReg16Bits(ATD0DIEN, 0xFFEFU);      
  /* ### MC9S12XEP100_144 "Cpu" init code ... */
  /* ### BitIO "wdi" init code ... */
  /* ### TimerInt "Timer" init code ... */
  /* ###  "CAN0" init code ... */
  CAN0_Init();
  /* ###  "CAN1" init code ... */
  CAN1_Init();
  /* ###  "CAN4" init code ... */
  CAN4_Init();
  /* ### BitIO "RELAY_HEAT" init code ... */
  /* ### BitIO "ISO_CTRL_POS" init code ... */
  /* ### BitIO "ISO_CTRL_NEG" init code ... */
  /* ### BitIO "CPUDI1" init code ... */
  /* ### BitIO "CPU_CS1" init code ... */
  /* ### BitIO "CPU_SCK" init code ... */
  /* ### BitIO "CPU_MOSI" init code ... */
  /* ### BitIO "CPU_MISO1" init code ... */
  /* ### BitIO "CPU_CS2" init code ... */
  /* ### BitIO "CPU_MISO2" init code ... */
  /* ### BitIO "CPU_SUMV_SDA" init code ... */
  Shadow_K &= 0xDFU;                   /* Initialize pin shadow variable bit */
  /* ### BitIO "CPU_SUMV_SCL" init code ... */
  /* ### BitIO "CPU_SUMV_RDY" init code ... */
  /* ### BitIO "SUMV_POW" init code ... */
  /* ### BitIO "EN_POW2" init code ... */
  /* ### BitIO "BAL_SDA2" init code ... */
  Shadow_C |= (byte)0x02U;             /* Initialize pin shadow variable bit */
  /* ### BitIO "EN_POW1" init code ... */
  /* ### BitIO "BAL_SDA1" init code ... */
  Shadow_C |= (byte)0x08U;             /* Initialize pin shadow variable bit */
  /* ### BitIO "ExternFlash_Rst" init code ... */
  Shadow_M &= 0xBFU;                   /* Initialize pin shadow variable bit */
  /* ### BitIO "ExternFlash_Cs" init code ... */
  Shadow_M &= 0x7FU;                   /* Initialize pin shadow variable bit */
  /* ### BitIO "ExternFlash_Sck" init code ... */
  Shadow_S &= 0xFDU;                   /* Initialize pin shadow variable bit */
  /* ### BitIO "ExternFlash_Si" init code ... */
  Shadow_S &= 0xFBU;                   /* Initialize pin shadow variable bit */
  /* ### BitIO "ExternFlash_So" init code ... */
  Shadow_H &= 0xEFU;                   /* Initialize pin shadow variable bit */
  /* ### BitIO "ExternTimer_Int" init code ... */
  /* ### BitIO "ExternTimer_Scl" init code ... */
  Shadow_D &= 0xFBU;                   /* Initialize pin shadow variable bit */
  /* ### BitIO "ExternTimer_Sda" init code ... */
  Shadow_D &= 0xF7U;                   /* Initialize pin shadow variable bit */
  /* ### BitIO "PORTA0" init code ... */
  /* ### BitIO "PORTA1" init code ... */
  /* ### BitIO "PORTA2" init code ... */
  /* ### BitIO "RELAY_POS" init code ... */
  /* ### BitIO "RELAY_NEG" init code ... */
  /* ### BitIO "RELAY_PRE" init code ... */
  /* ### BitIO "RELAY_FAN" init code ... */
  /* ###  "AI1" init code ... */
  AI1_Init();
  /* ### BitIO "CHG_CAN_POW" init code ... */
  /* ### BitIO "CPUCAN_CAR_EN" init code ... */
  /* ### BitIO "CPUCAN_INT_EN" init code ... */
  /* ### BitIO "CURPOWER" init code ... */
  /* ### BitIO "CPUCINT" init code ... */
  /* ### BitIO "CPUCSO" init code ... */
  /* ### BitIO "CPUCSI" init code ... */
  /* ### BitIO "CPUCSCK" init code ... */
  /* ### BitIO "CPUCCS" init code ... */
  /* ### BitIO "ExtEE_Sck" init code ... */
  /* ### BitIO "ExtEE_Sda" init code ... */
  Shadow_J &= 0xBFU;                   /* Initialize pin shadow variable bit */
  /* ### BitIO "ExtEE_Wp" init code ... */
  Shadow_K &= 0x7FU;                   /* Initialize pin shadow variable bit */
  /* ### IntEEPROM "CPUEE" init code ... */
  CPUEE_Init();
  /* ### BitIO "EN_POW3" init code ... */
  /* ### BitIO "EN_POW4" init code ... */
  /* ### BitIO "EN_CELL" init code ... */
  /* ### BitIO "DRDY_CELL" init code ... */
  /* ###  Synchro master "SPI2IF" init code ... */
  SPI2IF_Init();
  /* ###  WatchDog "IntWatchDog" init code ... */
  /* ### BitIO "CPUDI2" init code ... */
  /* ### Timer capture encapsulation "AC_CP_IOC" init code ... */
  AC_CP_IOC_Init();
  /* ### BitIO "CPU_CHG_S" init code ... */
  /* ### BitIO "DO_CON" init code ... */
  /* Common peripheral initialization - ENABLE */
  /* ECT_TSCR1: TEN=1,TSWAI=0,TSFRZ=0,TFFCA=0,PRNT=0,??=0,??=0,??=0 */
  setReg8(ECT_TSCR1, 0x80U);            
  __DI();                              /* Disable interrupts */
}

/*lint -save  -e950 Disable MISRA rule (1.1) checking. */
/* Initialization of the CPU registers in FLASH */
/*lint -restore Enable MISRA rule (1.1) checking. */

#pragma CODE_SEG __NEAR_SEG NON_BANKED

/*
** ===================================================================
**     Method      :  _EntryPoint (component MC9S12XEP100_144)
**
**     Description :
**         Initializes the whole system like timing and so on. At the end 
**         of this function, the C startup is invoked to initialize stack,
**         memory areas and so on.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
extern void _Startup(void);            /* Forward declaration of external startup function declared in file Start12.c */

/*** !!! Here you can place your own code using property "User data declarations" on the build options tab of the CPU component. !!! ***/


#pragma OPTION ADD "-Onf"              /* 'Create Sub-Functions with Common Code optimalization' must be disabled because stack is not yet initialized */

#pragma NO_FRAME                       /* Suppress generation of frame code */
#pragma NO_EXIT                        /* Suppress generation of exit from a function */
void _EntryPoint(void)
{

  /*** !!! Here you can place your own code using property "User code before PE initialization" on the build options tab of the CPU compoennt. !!! ***/

  /* ### MC9S12XEP100_144 "Cpu" init code ... */
  /*  PE initialization code after reset */
  /* MMCCTL1: TGMRAMON=0,??=0,EEEIFRON=0,PGMIFRON=0,RAMHM=0,EROMON=0,ROMHM=0,ROMON=1 */
  setReg8(MMCCTL1, 0x01U);              
  /* DIRECT: DP15=0,DP14=0,DP13=0,DP12=0,DP11=0,DP10=0,DP9=0,DP8=0 */
  setReg8(DIRECT, 0x00U);               
  /* ECLKCTL: NECLK=1,NCLKX2=1,DIV16=0,EDIV4=0,EDIV3=0,EDIV2=0,EDIV1=0,EDIV0=0 */
  setReg8(ECLKCTL, 0xC0U);              
  /*  System clock initialization */
  /* CLKSEL: PLLSEL=0,PSTP=0,XCLKS=0,??=0,PLLWAI=0,??=0,RTIWAI=0,COPWAI=0 */
  setReg8(CLKSEL, 0x00U);              /* Select clock source from XTAL and set bits in CLKSEL reg. */ 
  /* PLLCTL: CME=1,PLLON=0,FM1=0,FM0=0,FSTWKP=0,PRE=0,PCE=0,SCME=1 */
  setReg8(PLLCTL, 0x81U);              /* Disable the PLL */ 
  /* SYNR: VCOFRQ1=1,VCOFRQ0=1,SYNDIV5=0,SYNDIV4=0,SYNDIV3=0,SYNDIV2=1,SYNDIV1=0,SYNDIV0=1 */
  setReg8(SYNR, 0xC5U);                /* Set the multiplier register */ 
  /* REFDV: REFFRQ1=1,REFFRQ0=0,REFDIV5=0,REFDIV4=0,REFDIV3=0,REFDIV2=0,REFDIV1=0,REFDIV0=0 */
  setReg8(REFDV, 0x80U);               /* Set the divider register */ 
  /* POSTDIV: ??=0,??=0,??=0,POSTDIV4=0,POSTDIV3=0,POSTDIV2=0,POSTDIV1=0,POSTDIV0=0 */
  setReg8(POSTDIV, 0x00U);             /* Set the post divider register */ 
  /* PLLCTL: CME=1,PLLON=1,FM1=0,FM0=0,FSTWKP=0,PRE=0,PCE=0,SCME=1 */
  setReg8(PLLCTL, 0xC1U);               
  while(CRGFLG_LOCK == 0U) {           /* Wait until the PLL is within the desired tolerance of the target frequency */
  }
  /* CLKSEL: PLLSEL=1 */
  setReg8Bits(CLKSEL, 0x80U);          /* Select clock source from PLL */ 
  /* VREGHTCL: ??=0,??=0,VSEL=0,VAE=1,HTEN=0,HTDS=0,HTIE=0,HTIF=0 */
  setReg8(VREGHTCL, 0x10U);             
  /*** End of PE initialization code after reset ***/

  /*** !!! Here you can place your own code using property "User code after PE initialization" on the build options tab of the CPU component. !!! ***/

  /*lint -save  -e950 Disable MISRA rule (1.1) checking. */
  __asm("jmp _Startup");               /* Jump to C startup code */
  /*lint -restore Enable MISRA rule (1.1) checking. */
}

#pragma CODE_SEG DEFAULT
/* END Cpu. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
