/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : DO_CON.c
**     Project   : mcal
**     Processor : MC9S12XEP100MAG
**     Component : BitIO
**     Version   : Component 02.075, Driver 03.14, CPU db: 3.00.036
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2016/6/12, 10:05
**     Abstract  :
**         This component "BitIO" implements an one-bit input/output.
**         It uses one bit/pin of a port.
**         Note: This component is set to work in Output direction only.
**         Methods of this component are mostly implemented as a macros
**         (if supported by target language and compiler).
**     Settings  :
**         Used pin                    :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       76            |  PA3_ADDR11_IVD11
**             ----------------------------------------------------
**
**         Port name                   : A
**
**         Bit number (in port)        : 3
**         Bit mask of the port        : $0008
**
**         Initial direction           : Output (direction cannot be changed)
**         Initial output value        : 0
**         Initial pull option         : off
**
**         Port data register          : PORTA     [$0000]
**         Port control register       : DDRA      [$0002]
**
**         Optimization for            : speed
**     Contents  :
**         GetVal - bool DO_CON_GetVal(void);
**         PutVal - void DO_CON_PutVal(bool Val);
**         ClrVal - void DO_CON_ClrVal(void);
**         SetVal - void DO_CON_SetVal(void);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE DO_CON. */

#include "DO_CON.h"
  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"

#pragma DATA_SEG DO_CON_DATA           /* Select data segment "DO_CON_DATA" */
#pragma CODE_SEG DO_CON_CODE
#pragma CONST_SEG DO_CON_CONST         /* Constant section for this module */
/*
** ===================================================================
**     Method      :  DO_CON_GetVal (component BitIO)
**
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pin and returns it
**           b) direction = Output : returns the last written value
**         Note: This component is set to work in Output direction only.
**     Parameters  : None
**     Returns     :
**         ---             - Input value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)

** ===================================================================
*/
/*
bool DO_CON_GetVal(void)

**  This method is implemented as a macro. See DO_CON.h file.  **
*/

/*
** ===================================================================
**     Method      :  DO_CON_PutVal (component BitIO)
**
**     Description :
**         This method writes the new output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val             - Output value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)
**     Returns     : Nothing
** ===================================================================
*/
void DO_CON_PutVal(bool Val)
{
  if (Val) {
    setReg8Bits(PORTA, 0x08U);         /* PA3=0x01U */
  } else { /* !Val */
    clrReg8Bits(PORTA, 0x08U);         /* PA3=0x00U */
  } /* !Val */
}

/*
** ===================================================================
**     Method      :  DO_CON_ClrVal (component BitIO)
**
**     Description :
**         This method clears (sets to zero) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void DO_CON_ClrVal(void)

**  This method is implemented as a macro. See DO_CON.h file.  **
*/

/*
** ===================================================================
**     Method      :  DO_CON_SetVal (component BitIO)
**
**     Description :
**         This method sets (sets to one) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void DO_CON_SetVal(void)

**  This method is implemented as a macro. See DO_CON.h file.  **
*/


/* END DO_CON. */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
