/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : ExternFlash_Rst.c
**     Project   : mcal
**     Processor : MC9S12XEP100MAG
**     Component : BitIO
**     Version   : Component 02.075, Driver 03.14, CPU db: 3.00.036
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2016/1/9, 9:28
**     Abstract  :
**         This component "BitIO" implements an one-bit input/output.
**         It uses one bit/pin of a port.
**         Note: This component is set to work in Output direction only.
**         Methods of this component are mostly implemented as a macros
**         (if supported by target language and compiler).
**     Settings  :
**         Used pin                    :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       118           |  PM6_RxCAN3_RxCAN4_RxD3
**             ----------------------------------------------------
**
**         Port name                   : M
**
**         Bit number (in port)        : 6
**         Bit mask of the port        : $0040
**
**         Initial direction           : Output (direction cannot be changed)
**         Initial output value        : 0
**         Initial pull option         : off
**
**         Port data register          : PTM       [$0250]
**         Port control register       : DDRM      [$0252]
**
**         Optimization for            : speed
**     Contents  :
**         SetInput  - void ExternFlash_Rst_SetInput(void);
**         SetOutput - void ExternFlash_Rst_SetOutput(void);
**         GetVal    - bool ExternFlash_Rst_GetVal(void);
**         ClrVal    - void ExternFlash_Rst_ClrVal(void);
**         SetVal    - void ExternFlash_Rst_SetVal(void);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE ExternFlash_Rst. */

#include "ExternFlash_Rst.h"
  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"

#pragma DATA_SEG ExternFlash_Rst_DATA  /* Select data segment "ExternFlash_Rst_DATA" */
#pragma CODE_SEG ExternFlash_Rst_CODE
#pragma CONST_SEG ExternFlash_Rst_CONST /* Constant section for this module */
/*
** ===================================================================
**     Method      :  ExternFlash_Rst_GetVal (component BitIO)
**
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pin and returns it
**           b) direction = Output : returns the last written value
**         Note: This component is set to work in Output direction only.
**     Parameters  : None
**     Returns     :
**         ---             - Input value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)

** ===================================================================
*/
/*
bool ExternFlash_Rst_GetVal(void)

**  This method is implemented as a macro. See ExternFlash_Rst.h file.  **
*/

/*
** ===================================================================
**     Method      :  ExternFlash_Rst_ClrVal (component BitIO)
**
**     Description :
**         This method clears (sets to zero) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void ExternFlash_Rst_ClrVal(void)

**  This method is implemented as a macro. See ExternFlash_Rst.h file.  **
*/

/*
** ===================================================================
**     Method      :  ExternFlash_Rst_SetVal (component BitIO)
**
**     Description :
**         This method sets (sets to one) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void ExternFlash_Rst_SetVal(void)

**  This method is implemented as a macro. See ExternFlash_Rst.h file.  **
*/

/*
** ===================================================================
**     Method      :  ExternFlash_Rst_SetInput (component BitIO)
**
**     Description :
**         This method sets direction of the component to input.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void ExternFlash_Rst_SetInput(void)
{
  clrReg8Bits(DDRM, 0x40U);            /* DDRM6=0x00U */
}

/*
** ===================================================================
**     Method      :  ExternFlash_Rst_SetOutput (component BitIO)
**
**     Description :
**         This method sets direction of the component to output.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void ExternFlash_Rst_SetOutput(void)
{
  setReg8(PTM, (getReg8(PTM) & (byte)(~(byte)0x40U)) | (Shadow_M & 0x40U)); /* PTM6=Shadow_M[bit 6] */
  setReg8Bits(DDRM, 0x40U);            /* DDRM6=0x01U */
}


/* END ExternFlash_Rst. */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
