// ErrorMacro.h
#ifndef ERRORMACRO_H
#define ERRORMACRO_H


#include "Ecu.h"
#include "SchIf.h"


// macro define should be adjusted for different projects
// you could define new macro if new project needs
#define ERROR_TM_MS(ms)  ((ms) / 10) // ms must can be divided by 10

#if ((ECU_CATEGORY == M_BCU_C) || (ECU_CATEGORY == M_BCU_D))

#define ERR_CNT_SET_SUMV_HIGH_L1         (ERROR_TM_MS(5000))
#define ERR_CNT_SET_SUMV_HIGH_L2         (ERROR_TM_MS(5000))
#define ERR_CNT_SET_SUMV_HIGH_L3         (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_SUMV_HIGH_L1         (ERROR_TM_MS(5000))
#define ERR_CNT_CLR_SUMV_HIGH_L2         (ERROR_TM_MS(5000))
#define ERR_CNT_CLR_SUMV_HIGH_L3         (ERROR_TM_MS(2000))
#define ERR_THRHD_HYSTRS_SUMV_HIGH_L1    (20) // 0.1V
#define ERR_THRHD_HYSTRS_SUMV_HIGH_L2    (20) // 0.1V
#define ERR_THRHD_HYSTRS_SUMV_HIGH_L3    (10) // 0.1V

#define ERR_CNT_SET_SUMV_LOW_L1         (ERROR_TM_MS(5000))
#define ERR_CNT_SET_SUMV_LOW_L2         (ERROR_TM_MS(5000))
#define ERR_CNT_SET_SUMV_LOW_L3         (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_SUMV_LOW_L1         (ERROR_TM_MS(5000))
#define ERR_CNT_CLR_SUMV_LOW_L2         (ERROR_TM_MS(5000))
#define ERR_CNT_CLR_SUMV_LOW_L3         (ERROR_TM_MS(2000))
#define ERR_THRHD_HYSTRS_SUMV_LOW_L1    (20) // 0.1V
#define ERR_THRHD_HYSTRS_SUMV_LOW_L2    (20) // 0.1V
#define ERR_THRHD_HYSTRS_SUMV_LOW_L3    (10) // 0.1V

#define ERR_CNT_SET_TEMPER_HIGH_L1       (ERROR_TM_MS(6000))
#define ERR_CNT_SET_TEMPER_HIGH_L2       (ERROR_TM_MS(6000))
#define ERR_CNT_SET_TEMPER_HIGH_L3       (ERROR_TM_MS(3000))
#define ERR_CNT_CLR_TEMPER_HIGH_L1       (ERROR_TM_MS(6000))
#define ERR_CNT_CLR_TEMPER_HIGH_L2       (ERROR_TM_MS(6000))
#define ERR_CNT_CLR_TEMPER_HIGH_L3       (ERROR_TM_MS(3000))
#define ERR_THRHD_HYSTRS_TEMPER_HIGH_L1  (2) // 1'C
#define ERR_THRHD_HYSTRS_TEMPER_HIGH_L2  (2) // 1'C
#define ERR_THRHD_HYSTRS_TEMPER_HIGH_L3  (1) // 1'C

#define ERR_CNT_SET_TEMPER_LOW_L1       (ERROR_TM_MS(6000))
#define ERR_CNT_SET_TEMPER_LOW_L2       (ERROR_TM_MS(6000))
#define ERR_CNT_SET_TEMPER_LOW_L3       (ERROR_TM_MS(3000))
#define ERR_CNT_CLR_TEMPER_LOW_L1       (ERROR_TM_MS(6000))
#define ERR_CNT_CLR_TEMPER_LOW_L2       (ERROR_TM_MS(6000))
#define ERR_CNT_CLR_TEMPER_LOW_L3       (ERROR_TM_MS(3000))
#define ERR_THRHD_HYSTRS_TEMPER_LOW_L1  (2) // 1'C
#define ERR_THRHD_HYSTRS_TEMPER_LOW_L2  (2) // 1'C
#define ERR_THRHD_HYSTRS_TEMPER_LOW_L3  (1) // 1'C

#define ERR_CNT_SET_DELTT_L1        (ERROR_TM_MS(6000))
#define ERR_CNT_SET_DELTT_L2        (ERROR_TM_MS(6000))
#define ERR_CNT_SET_DELTT_L3        (ERROR_TM_MS(3000))
#define ERR_CNT_CLR_DELTT_L1        (ERROR_TM_MS(6000))
#define ERR_CNT_CLR_DELTT_L2        (ERROR_TM_MS(6000))
#define ERR_CNT_CLR_DELTT_L3        (ERROR_TM_MS(3000))
#define ERR_THRHD_HYSTRS_DELTT_L1   (2) // 1'C
#define ERR_THRHD_HYSTRS_DELTT_L2   (2) // 1'C
#define ERR_THRHD_HYSTRS_DELTT_L3   (1) // 1'C

#define ERR_CNT_SET_DELTV_L1        (ERROR_TM_MS(5000))
#define ERR_CNT_SET_DELTV_L2        (ERROR_TM_MS(5000))
#define ERR_CNT_SET_DELTV_L3        (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_DELTV_L1        (ERROR_TM_MS(5000))
#define ERR_CNT_CLR_DELTV_L2        (ERROR_TM_MS(5000))
#define ERR_CNT_CLR_DELTV_L3        (ERROR_TM_MS(2000))
#define ERR_THRHD_HYSTRS_DELTV_L1   (30) // 1mv
#define ERR_THRHD_HYSTRS_DELTV_L2   (30) // 1mv
#define ERR_THRHD_HYSTRS_DELTV_L3   (15) // 1mv

#define ERR_CNT_SET_CELLV_HIGH_L1        (ERROR_TM_MS(5000))
#define ERR_CNT_SET_CELLV_HIGH_L2        (ERROR_TM_MS(5000))
#define ERR_CNT_SET_CELLV_HIGH_L3        (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_CELLV_HIGH_L1        (ERROR_TM_MS(5000))
#define ERR_CNT_CLR_CELLV_HIGH_L2        (ERROR_TM_MS(5000))
#define ERR_CNT_CLR_CELLV_HIGH_L3        (ERROR_TM_MS(2000))
#define ERR_THRHD_HYSTRS_CELLV_HIGH_L1   (20) // 1mv
#define ERR_THRHD_HYSTRS_CELLV_HIGH_L2   (20) // 1mv
#define ERR_THRHD_HYSTRS_CELLV_HIGH_L3   (10) // 1mv

#define ERR_CNT_SET_CELLV_LOW_L1        (ERROR_TM_MS(5000))
#define ERR_CNT_SET_CELLV_LOW_L2        (ERROR_TM_MS(5000))
#define ERR_CNT_SET_CELLV_LOW_L3        (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_CELLV_LOW_L1        (ERROR_TM_MS(5000))
#define ERR_CNT_CLR_CELLV_LOW_L2        (ERROR_TM_MS(5000))
#define ERR_CNT_CLR_CELLV_LOW_L3        (ERROR_TM_MS(2000))
#define ERR_THRHD_HYSTRS_CELLV_LOW_L1   (20) // 1mv
#define ERR_THRHD_HYSTRS_CELLV_LOW_L2   (20) // 1mv
#define ERR_THRHD_HYSTRS_CELLV_LOW_L3   (10) // 1mv

#define ERR_CNT_SET_CURCHG_L1       (ERROR_TM_MS(5000))
#define ERR_CNT_SET_CURCHG_L2       (ERROR_TM_MS(5000))
#define ERR_CNT_SET_CURCHG_L3       (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_CURCHG_L1       (ERROR_TM_MS(5000))
#define ERR_CNT_CLR_CURCHG_L2       (ERROR_TM_MS(5000))
#define ERR_CNT_CLR_CURCHG_L3       (ERROR_TM_MS(2000))
#define ERR_THRHD_HYSTRS_CURCHG_L1  (50) // 0.1A
#define ERR_THRHD_HYSTRS_CURCHG_L2  (50) // 0.1A
#define ERR_THRHD_HYSTRS_CURCHG_L3  (20) // 0.1A

#define ERR_CNT_SET_CURDCH_L1       (ERROR_TM_MS(5000))
#define ERR_CNT_SET_CURDCH_L2       (ERROR_TM_MS(5000))
#define ERR_CNT_SET_CURDCH_L3       (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_CURDCH_L1       (ERROR_TM_MS(5000))
#define ERR_CNT_CLR_CURDCH_L2       (ERROR_TM_MS(5000))
#define ERR_CNT_CLR_CURDCH_L3       (ERROR_TM_MS(2000))
#define ERR_THRHD_HYSTRS_CURDCH_L1  (50) // 0.1A
#define ERR_THRHD_HYSTRS_CURDCH_L2  (50) // 0.1A
#define ERR_THRHD_HYSTRS_CURDCH_L3  (20) // 0.1A

#define ERR_CNT_SET_CURFEEDBAK_L1       (ERROR_TM_MS(5000))
#define ERR_CNT_SET_CURFEEDBAK_L2       (ERROR_TM_MS(5000))
#define ERR_CNT_SET_CURFEEDBAK_L3       (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_CURFEEDBAK_L1       (ERROR_TM_MS(5000))
#define ERR_CNT_CLR_CURFEEDBAK_L2       (ERROR_TM_MS(5000))
#define ERR_CNT_CLR_CURFEEDBAK_L3       (ERROR_TM_MS(2000))
#define ERR_THRHD_HYSTRS_CURFEEDBAK_L1  (50) // 0.1A
#define ERR_THRHD_HYSTRS_CURFEEDBAK_L2  (50) // 0.1A
#define ERR_THRHD_HYSTRS_CURFEEDBAK_L3  (20) // 0.1A

#define ERR_CNT_SET_SOC_HIGH_L1          (ERROR_TM_MS(5000))
#define ERR_CNT_SET_SOC_HIGH_L2          (ERROR_TM_MS(5000))
#define ERR_CNT_SET_SOC_HIGH_L3          (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_SOC_HIGH_L1          (ERROR_TM_MS(5000))
#define ERR_CNT_CLR_SOC_HIGH_L2          (ERROR_TM_MS(5000))
#define ERR_CNT_CLR_SOC_HIGH_L3          (ERROR_TM_MS(2000))
#define ERR_THRHD_HYSTRS_SOC_HIGH_L1     (15) // 0.1%
#define ERR_THRHD_HYSTRS_SOC_HIGH_L2     (15) // 0.1%
#define ERR_THRHD_HYSTRS_SOC_HIGH_L3     (10) // 0.1%

#define ERR_CNT_SET_SOC_LOW_L1          (ERROR_TM_MS(5000))
#define ERR_CNT_SET_SOC_LOW_L2          (ERROR_TM_MS(5000))
#define ERR_CNT_SET_SOC_LOW_L3          (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_SOC_LOW_L1          (ERROR_TM_MS(5000))
#define ERR_CNT_CLR_SOC_LOW_L2          (ERROR_TM_MS(5000))
#define ERR_CNT_CLR_SOC_LOW_L3          (ERROR_TM_MS(2000))
#define ERR_THRHD_HYSTRS_SOC_LOW_L1     (15) // 0.1%
#define ERR_THRHD_HYSTRS_SOC_LOW_L2     (15) // 0.1%
#define ERR_THRHD_HYSTRS_SOC_LOW_L3     (10) // 0.1%

#define ERR_CNT_SET_INTRES_L1       (ERROR_TM_MS(6000))
#define ERR_CNT_SET_INTRES_L2       (ERROR_TM_MS(6000))
#define ERR_CNT_SET_INTRES_L3       (ERROR_TM_MS(3000))
#define ERR_CNT_CLR_INTRES_L1       (ERROR_TM_MS(6000))
#define ERR_CNT_CLR_INTRES_L2       (ERROR_TM_MS(6000))
#define ERR_CNT_CLR_INTRES_L3       (ERROR_TM_MS(3000))
#define ERR_THRHD_HYSTRS_INTRES_L1  (10) // 0.1mO
#define ERR_THRHD_HYSTRS_INTRES_L2  (10) // 0.1mO
#define ERR_THRHD_HYSTRS_INTRES_L3  (10) // 0.1mO

#define ERR_CNT_SET_TPOLE_L1        (ERROR_TM_MS(6000))
#define ERR_CNT_SET_TPOLE_L2        (ERROR_TM_MS(6000))
#define ERR_CNT_SET_TPOLE_L3        (ERROR_TM_MS(3000))
#define ERR_CNT_CLR_TPOLE_L1        (ERROR_TM_MS(6000))
#define ERR_CNT_CLR_TPOLE_L2        (ERROR_TM_MS(6000))
#define ERR_CNT_CLR_TPOLE_L3        (ERROR_TM_MS(3000))
#define ERR_THRHD_HYSTRS_TPOLE_L1   (2) // 1'C
#define ERR_THRHD_HYSTRS_TPOLE_L2   (2) // 1'C
#define ERR_THRHD_HYSTRS_TPOLE_L3   (1) // 1'C

#define ERR_CNT_SET_SOH_L1          (ERROR_TM_MS(5000))
#define ERR_CNT_SET_SOH_L2          (ERROR_TM_MS(5000))
#define ERR_CNT_SET_SOH_L3          (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_SOH_L1          (ERROR_TM_MS(5000))
#define ERR_CNT_CLR_SOH_L2          (ERROR_TM_MS(5000))
#define ERR_CNT_CLR_SOH_L3          (ERROR_TM_MS(2000))
#define ERR_THRHD_HYSTRS_SOH_L1     (15) // 0.1%
#define ERR_THRHD_HYSTRS_SOH_L2     (15) // 0.1%
#define ERR_THRHD_HYSTRS_SOH_L3     (10) // 0.1%

#define ERR_CNT_SET_POWVOLT_HIGH_L1      (ERROR_TM_MS(2000))
#define ERR_CNT_SET_POWVOLT_HIGH_L2      (ERROR_TM_MS(2000))
#define ERR_CNT_SET_POWVOLT_HIGH_L3      (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_POWVOLT_HIGH_L1      (ERROR_TM_MS(1000))
#define ERR_CNT_CLR_POWVOLT_HIGH_L2      (ERROR_TM_MS(1000))
#define ERR_CNT_CLR_POWVOLT_HIGH_L3      (ERROR_TM_MS(1000))
#define ERR_THRHD_HYSTRS_POWVOLT_HIGH_L1 (5) // 0.5v
#define ERR_THRHD_HYSTRS_POWVOLT_HIGH_L2 (5) // 0.5v
#define ERR_THRHD_HYSTRS_POWVOLT_HIGH_L3 (5) // 0.5v

#define ERR_CNT_SET_POWVOLT_LOW_L1      (ERROR_TM_MS(2000))
#define ERR_CNT_SET_POWVOLT_LOW_L2      (ERROR_TM_MS(2000))
#define ERR_CNT_SET_POWVOLT_LOW_L3      (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_POWVOLT_LOW_L1      (ERROR_TM_MS(1000))
#define ERR_CNT_CLR_POWVOLT_LOW_L2      (ERROR_TM_MS(1000))
#define ERR_CNT_CLR_POWVOLT_LOW_L3      (ERROR_TM_MS(1000))
#define ERR_THRHD_HYSTRS_POWVOLT_LOW_L1 (5) // 0.5v
#define ERR_THRHD_HYSTRS_POWVOLT_LOW_L2 (5) // 0.5v
#define ERR_THRHD_HYSTRS_POWVOLT_LOW_L3 (5) // 0.5v

#define ERR_THRHD_POWVOLT_HIGH_L1   (300) // 30V
#define ERR_THRHD_POWVOLT_HIGH_L2   (310) // 31V
#define ERR_THRHD_POWVOLT_HIGH_L3   (320) // 32V

#define ERR_THRHD_POWVOLT_LOW_L1    (80)  // 8V
#define ERR_THRHD_POWVOLT_LOW_L2    (70)  // 7V
#define ERR_THRHD_POWVOLT_LOW_L3    (60)  // 6V

//#define ERR_CHG_CUR_TABLE
//#define ERR_DIS_CUR_TABLE
//#define ERR_FDB_CUR_TABLE

#define ERR_CHG_CUR_GAIN_L1  10
#define ERR_CHG_CUR_GAIN_L2  12
#define ERR_CHG_CUR_GAIN_L3  15

#define ERR_DIS_CUR_GAIN_L1  10
#define ERR_DIS_CUR_GAIN_L2  12
#define ERR_DIS_CUR_GAIN_L3  15

#define ERR_FDB_CUR_GAIN_L1  10
#define ERR_FDB_CUR_GAIN_L2  12
#define ERR_FDB_CUR_GAIN_L3  15

#define ERR_CNT_CAN4_L1       (ERROR_TM_MS(5000)) 
#define ERR_CLR_CAN4_L1_EN  1              // 1: can clear err_code bit, 0:hold 
#define ERR_CNT_CAN4_L2       (ERROR_TM_MS(5000))
#define ERR_CLR_CAN4_L2_EN  1 
#define ERR_CNT_CAN4_L3       (ERROR_TM_MS(5000))
#define ERR_CLR_CAN4_L3_EN  1   

#endif//#if ((ECU_CATEGORY == M_BCU_C) || (ECU_CATEGORY == M_BCU_D))


#if ((ECU_CATEGORY == M_BMU) || (ECU_CATEGORY == M_BMU_R))

#define ERR_CNT_SET_CELLV_HIGH_L1        (ERROR_TM_MS(5000))
#define ERR_CNT_SET_CELLV_HIGH_L2        (ERROR_TM_MS(5000))
#define ERR_CNT_SET_CELLV_HIGH_L3        (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_CELLV_HIGH_L1        (ERROR_TM_MS(5000))
#define ERR_CNT_CLR_CELLV_HIGH_L2        (ERROR_TM_MS(5000))
#define ERR_CNT_CLR_CELLV_HIGH_L3        (ERROR_TM_MS(2000))
#define ERR_THRHD_HYSTRS_CELLV_HIGH_L1   (20) // 1mV
#define ERR_THRHD_HYSTRS_CELLV_HIGH_L2   (20) // 1mV
#define ERR_THRHD_HYSTRS_CELLV_HIGH_L3   (10) // 1mV

#define ERR_CNT_SET_CELLV_LOW_L1        (ERROR_TM_MS(5000))
#define ERR_CNT_SET_CELLV_LOW_L2        (ERROR_TM_MS(5000))
#define ERR_CNT_SET_CELLV_LOW_L3        (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_CELLV_LOW_L1        (ERROR_TM_MS(5000))
#define ERR_CNT_CLR_CELLV_LOW_L2        (ERROR_TM_MS(5000))
#define ERR_CNT_CLR_CELLV_LOW_L3        (ERROR_TM_MS(2000))
#define ERR_THRHD_HYSTRS_CELLV_LOW_L1   (20) // 1mV
#define ERR_THRHD_HYSTRS_CELLV_LOW_L2   (20) // 1mV
#define ERR_THRHD_HYSTRS_CELLV_LOW_L3   (10) // 1mV

#define ERR_CNT_SET_DELTV_L1        (ERROR_TM_MS(5000))
#define ERR_CNT_SET_DELTV_L2        (ERROR_TM_MS(5000))
#define ERR_CNT_SET_DELTV_L3        (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_DELTV_L1        (ERROR_TM_MS(5000))
#define ERR_CNT_CLR_DELTV_L2        (ERROR_TM_MS(5000))
#define ERR_CNT_CLR_DELTV_L3        (ERROR_TM_MS(2000))
#define ERR_THRHD_HYSTRS_DELTV_L1   (30) // 1mV
#define ERR_THRHD_HYSTRS_DELTV_L2   (30) // 1mV
#define ERR_THRHD_HYSTRS_DELTV_L3   (15) // 1mV

#define ERR_CNT_SET_TEMPER_HIGH_L1       (ERROR_TM_MS(6000))
#define ERR_CNT_SET_TEMPER_HIGH_L2       (ERROR_TM_MS(6000))
#define ERR_CNT_SET_TEMPER_HIGH_L3       (ERROR_TM_MS(3000))
#define ERR_CNT_CLR_TEMPER_HIGH_L1       (ERROR_TM_MS(6000))
#define ERR_CNT_CLR_TEMPER_HIGH_L2       (ERROR_TM_MS(6000))
#define ERR_CNT_CLR_TEMPER_HIGH_L3       (ERROR_TM_MS(3000))
#define ERR_THRHD_HYSTRS_TEMPER_HIGH_L1  (2) // 1'C
#define ERR_THRHD_HYSTRS_TEMPER_HIGH_L2  (2) // 1'C
#define ERR_THRHD_HYSTRS_TEMPER_HIGH_L3  (1) // 1'C

#define ERR_CNT_SET_TEMPER_LOW_L1       (ERROR_TM_MS(6000))
#define ERR_CNT_SET_TEMPER_LOW_L2       (ERROR_TM_MS(6000))
#define ERR_CNT_SET_TEMPER_LOW_L3       (ERROR_TM_MS(3000))
#define ERR_CNT_CLR_TEMPER_LOW_L1       (ERROR_TM_MS(6000))
#define ERR_CNT_CLR_TEMPER_LOW_L2       (ERROR_TM_MS(6000))
#define ERR_CNT_CLR_TEMPER_LOW_L3       (ERROR_TM_MS(3000))
#define ERR_THRHD_HYSTRS_TEMPER_LOW_L1  (2) // 1'C
#define ERR_THRHD_HYSTRS_TEMPER_LOW_L2  (2) // 1'C
#define ERR_THRHD_HYSTRS_TEMPER_LOW_L3  (1) // 1'C

#define ERR_CNT_SET_DELTT_L1        (ERROR_TM_MS(6000))
#define ERR_CNT_SET_DELTT_L2        (ERROR_TM_MS(6000))
#define ERR_CNT_SET_DELTT_L3        (ERROR_TM_MS(3000))
#define ERR_CNT_CLR_DELTT_L1        (ERROR_TM_MS(6000))
#define ERR_CNT_CLR_DELTT_L2        (ERROR_TM_MS(6000))
#define ERR_CNT_CLR_DELTT_L3        (ERROR_TM_MS(3000))
#define ERR_THRHD_HYSTRS_DELTT_L1   (2) // 1'C
#define ERR_THRHD_HYSTRS_DELTT_L2   (2) // 1'C
#define ERR_THRHD_HYSTRS_DELTT_L3   (1) // 1'C

#define ERR_CNT_SET_SOC_HIGH_L1          (ERROR_TM_MS(5000))
#define ERR_CNT_SET_SOC_HIGH_L2          (ERROR_TM_MS(5000))
#define ERR_CNT_SET_SOC_HIGH_L3          (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_SOC_HIGH_L1          (ERROR_TM_MS(5000))
#define ERR_CNT_CLR_SOC_HIGH_L2          (ERROR_TM_MS(5000))
#define ERR_CNT_CLR_SOC_HIGH_L3          (ERROR_TM_MS(2000))
#define ERR_THRHD_HYSTRS_SOC_HIGH_L1     (15) // 0.1%
#define ERR_THRHD_HYSTRS_SOC_HIGH_L2     (15) // 0.1%
#define ERR_THRHD_HYSTRS_SOC_HIGH_L3     (10) // 0.1%

#define ERR_CNT_SET_SOC_LOW_L1          (ERROR_TM_MS(5000))
#define ERR_CNT_SET_SOC_LOW_L2          (ERROR_TM_MS(5000))
#define ERR_CNT_SET_SOC_LOW_L3          (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_SOC_LOW_L1          (ERROR_TM_MS(5000))
#define ERR_CNT_CLR_SOC_LOW_L2          (ERROR_TM_MS(5000))
#define ERR_CNT_CLR_SOC_LOW_L3          (ERROR_TM_MS(2000))
#define ERR_THRHD_HYSTRS_SOC_LOW_L1     (15) // 0.1%
#define ERR_THRHD_HYSTRS_SOC_LOW_L2     (15) // 0.1%
#define ERR_THRHD_HYSTRS_SOC_LOW_L3     (10) // 0.1%

#define ERR_CNT_SET_CURCHG_L1       (ERROR_TM_MS(5000))
#define ERR_CNT_SET_CURCHG_L2       (ERROR_TM_MS(5000))
#define ERR_CNT_SET_CURCHG_L3       (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_CURCHG_L1       (ERROR_TM_MS(5000))
#define ERR_CNT_CLR_CURCHG_L2       (ERROR_TM_MS(5000))
#define ERR_CNT_CLR_CURCHG_L3       (ERROR_TM_MS(2000))
#define ERR_THRHD_HYSTRS_CURCHG_L1  (50) // 0.1A
#define ERR_THRHD_HYSTRS_CURCHG_L2  (50) // 0.1A
#define ERR_THRHD_HYSTRS_CURCHG_L3  (20) // 0.1A

#define ERR_CNT_SET_CURDCH_L1       (ERROR_TM_MS(5000))
#define ERR_CNT_SET_CURDCH_L2       (ERROR_TM_MS(5000))
#define ERR_CNT_SET_CURDCH_L3       (ERROR_TM_MS(2000))
#define ERR_CNT_CLR_CURDCH_L1       (ERROR_TM_MS(5000))
#define ERR_CNT_CLR_CURDCH_L2       (ERROR_TM_MS(5000))
#define ERR_CNT_CLR_CURDCH_L3       (ERROR_TM_MS(2000))
#define ERR_THRHD_HYSTRS_CURDCH_L1  (50) // 0.1A
#define ERR_THRHD_HYSTRS_CURDCH_L2  (50) // 0.1A
#define ERR_THRHD_HYSTRS_CURDCH_L3  (20) // 0.1A

#define CHG_ST_OFF  0x00
#define CHG_ST_ON   0x01

#endif//#if ((ECU_CATEGORY == M_BMU) || (ECU_CATEGORY == M_BMU_R))

#endif /* ERRORMACRO_H */