/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : IntWatchDog.h
**     Project   : mcal
**     Processor : MC9S12XEP100MAG
**     Component : WatchDog
**     Version   : Component 02.134, Driver 01.17, CPU db: 3.00.036
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2016/1/9, 9:28
**     Abstract  :
**         This device "WatchDog" implements a watchdog.
**         When enabled, the watchdog timer counts until it reaches
**         a critical value corresponding to the period specified
**         in 'Properties'. Then, the watchdog causes a CPU reset.
**         Applications may clear the timer before it reaches the critical
**         value. The timer then restarts the watchdog counter.
**         Watchdog is used for increasing the safety of the system
**         (unforeseeable situations can cause system crash or an
**         infinite loop - watchdog can restart the system or handle
**         the situation).
**
**         Note: Watchdog can be enabled or disabled in the initialization
**               code only. If the watchdog is once enabled user have
**               to call Clear method in defined time intervals.
**     Settings  :
**         Watchdog causes             : Reset CPU
**
**         Initial Watchdog state      : Enabled
**
**         Mode of operation           : Normal
**
**         High speed mode
**           Watchdog period/frequency
**             microseconds            : 524288
**             milliseconds            : 524
**             seconds                 : 1
**             Hz                      : 2
**
**         Run register                : COPCTL    [$003C]
**         Mode register               : COPCTL    [$003C]
**         Prescaler register          : COPCTL    [$003C]
**     Contents  :
**         Clear - byte IntWatchDog_Clear(void);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __IntWatchDog
#define __IntWatchDog

/* MODULE IntWatchDog. */

#include "Cpu.h"

#pragma CODE_SEG IntWatchDog_CODE


/*
** ===================================================================
**     Method      :  IntWatchDog_Clear (component WatchDog)
**
**     Description :
**         Clears the watchdog timer (it makes the timer restart from
**         zero).
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED - The component is disabled
** ===================================================================
*/
byte IntWatchDog_Clear(void);



#pragma CODE_SEG DEFAULT

/* END IntWatchDog. */

#endif /* ifndef __IntWatchDog */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
